# Generated by Django 4.1.1 on 2022-09-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicSecretAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42)),
                ('age', models.IntegerField()),
                ('is_fake', models.BooleanField(default=True)),
                ('birthdate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'basic_secret',
            },
        ),
    ]
